name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: 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
        TARGET_REPO: JC96821/JC96821.github.io
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm run build
        BUILD_DIR: src/.vuepress/dist/
        CNAME: www.ydlcq.cn